[package]
name = "aurora_core"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora_derive = { version = "0.1", path = "../macros" }
bytemuck = { version = "1.16", features = ["derive"] }
flume = "0.11"
glam = { version = "0.27", features = ["bytemuck"] }
naga_oil = { git = "https://github.com/Elabajaba/naga_oil.git", branch = "wgpu-0.20" }
log = "0.4"
obj = "0.10.2"
png = "0.17.13"
pollster = "0.3"
wgpu = { version = "0.20", features = ["naga-ir"] }
