[package]
name = "aurora_chest"
version = "0.1.0"
edition = "2021"

[dependencies]
aurora_core = { version = "0.1", path = "../core" }
aurora_derive = { version = "0.1", path = "../macros" }
glam = "0.27"
naga_oil = { git = "https://github.com/Elabajaba/naga_oil.git", branch = "wgpu-0.20" }
palette = "0.7"
uuid = { version = "1.8", features = ["v4"] }
wgpu = { version = "0.20", features = ["naga-ir"] }
